opal:
  image: obiba/opal:latest
  ports:
  - "8843:8443"
  - "8880:8080"
  links:
  - mongo
  - rserver
  environment:
  - OPAL_ADMINISTRATOR_PASSWORD=password
  volumes:
  - /tmp/opal:/srv
rserver:
  image: obiba/opal-rserver:latest
  ports:
  - "6612:6312"
  - "6611:6311"
mongo:
  image: mongo
